#!/usr/bin/env bash
# Decision matrix for the PreToolUse guard.
#
# This exists because of one specific failure. The `**` → `*` rewrite was
# written as `${pat//\*\*/\*}`, which inserts a LITERAL BACKSLASH, so no scope
# ever matched and the guard permitted everything — while looking, from the
# outside, exactly like a guard that had nothing to block. Nothing in a normal
# session would have revealed it. A guard that silently allows is worse than no
# guard, because the operator believes they have one.
#
# Run: hooks/tests/test_guard.sh   (also `just check-guard` from the app repo)
set -uo pipefail

HERE=$(cd "$(dirname "$0")" && pwd)
GUARD="$HERE/../guard.sh"
command -v jq >/dev/null || { echo "SKIP: jq not installed"; exit 0; }

# Unroutable, so the liveness call fails fast. Failing open there must mean
# "assume still blocked", never "assume clear".
export HGD_BASE_URL="http://127.0.0.1:9"

T=$(mktemp -d)/repo
mkdir -p "$T/.humangated" "$T/src/billing/eu" "$T/src/ui"
stamp() { date -u -v"$1" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d "$2" +%Y-%m-%dT%H:%M:%SZ; }
FUTURE=$(stamp +2d '+2 days'); PAST=$(stamp -2d '-2 days'); NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
OLD=$(stamp -3H '-3 hours')

cat > "$T/.humangated/BLOCKED" <<EOF
# Open gates. Generated by HumanGated — do not hand-edit.
3f2a1b8c-0000-4000-8000-000000000001  required/abort   $FUTURE  $NOW  src/billing/**
7c9d0e1f-0000-4000-8000-000000000002  awaited/proceed  $FUTURE  $NOW  src/ui/**
a1b2c3d4-0000-4000-8000-000000000003  blocking/hold    -        $OLD  docs/**
b2c3d4e5-0000-4000-8000-000000000004  required/abort   $PAST    $NOW  legacy/**
EOF

pass=0; fail=0
check() {  # name  expected(ALLOW|DENY)  input-json
  local out got
  out=$(printf '%s' "$3" | "$GUARD" 2>/dev/null)
  [ -z "$out" ] && got=ALLOW || got=DENY
  if [ "$got" = "$2" ]; then
    pass=$((pass + 1)); printf '  ok   %s\n' "$1"
  else
    fail=$((fail + 1)); printf '  FAIL %s — wanted %s, got %s\n' "$1" "$2" "$got"
  fi
}
edit() { jq -nc --arg c "$1" --arg f "$2" '{cwd:$c,tool_name:"Edit",tool_input:{file_path:$f}}'; }
run()  { jq -nc --arg c "$1" --arg m "$2" '{cwd:$c,tool_name:"Bash",tool_input:{command:$m}}'; }

echo "guard decision matrix"

# The core: required/blocking hold the scope outright.
check "required: edit inside scope"       DENY  "$(edit "$T" "$T/src/billing/charge.py")"
check "required: edit nested under scope" DENY  "$(edit "$T/src" "$T/src/billing/eu/vat.py")"
check "blocking: edit inside scope"       DENY  "$(edit "$T" "$T/docs/api.md")"

# awaited permits preparing, never landing (ask-lifecycle §4).
check "awaited: edit inside scope"        ALLOW "$(edit "$T" "$T/src/ui/button.tsx")"
check "awaited: git commit in scope"      DENY  "$(run  "$T" "git commit -m wip src/ui/button.tsx")"
# A bare `git push` names no path but ships everything committed. The guard
# asks git what would actually go out; when git cannot say, it holds — a
# landing verb with an unknown blast radius is the case a gate exists for.
check "awaited: bare git push"            DENY  "$(run  "$T" "git push origin main")"
check "landing with unknowable reach"     DENY  "$(run  "$T" "terraform apply -auto-approve")"

# Reads are never blocked — over-blocking gets the plugin uninstalled.
check "read of a gated file"              ALLOW "$(run  "$T" "cat src/billing/charge.py")"
check "grep inside a gated dir"           ALLOW "$(run  "$T" "grep -r TODO src/billing")"
check "test run mentioning scope"         ALLOW "$(run  "$T" "pytest src/billing/tests")"

# Out of scope, and no ledger at all.
check "edit outside every scope"          ALLOW "$(edit "$T" "$T/README.md")"
check "no ledger anywhere"                ALLOW "$(edit "/tmp" "/tmp/whatever.py")"

# A passed deadline releases the gate locally: the engine has acted or is about to.
check "expired gate releases"             ALLOW "$(edit "$T" "$T/legacy/old.py")"

# Tools we do not police must never be touched.
check "Read is not intercepted"           ALLOW "$(jq -nc --arg c "$T" '{cwd:$c,tool_name:"Read",tool_input:{file_path:"src/billing/charge.py"}}')"

# Malformed input must fail OPEN, not crash the session.
check "empty stdin"                       ALLOW ""
check "garbage json"                      ALLOW "not json at all"
check "missing cwd"                       ALLOW "$(jq -nc '{tool_name:"Edit",tool_input:{file_path:"x"}}')"

# ── Standing sign-off rules ─────────────────────────────────────────────────
#
# A rule fires when there is NO open gate — the case the BLOCKED loop cannot
# see. It holds landing only: refusing edits under a governed path would make it
# impossible to write the change you then want reviewed.

R=$(mktemp -d)/repo
mkdir -p "$R/.humangated" "$R/src/billing" "$R/src/ui"
git -C "$R" init -q 2>/dev/null
git -C "$R" config user.email t@t.local 2>/dev/null
git -C "$R" config user.name t 2>/dev/null

cat > "$R/.humangated/RULES" <<EOF
# Standing sign-off rules. Generated by HumanGated — do not hand-edit.
src/billing/**	required	mike@partner.co	finance signs off refunds
src/ui/**	courtesy	-	-
EOF

# Something staged under a governed path, so `git commit` has a real blast radius.
echo "x" > "$R/src/billing/refunds.py"
git -C "$R" add -A 2>/dev/null

check "rule: edits are never held"        ALLOW "$(edit "$R" "$R/src/billing/refunds.py")"
check "rule: landing governed path held"  DENY  "$(run  "$R" "git commit -m wip")"
check "rule: non-landing command allowed" ALLOW "$(run  "$R" "pytest src/billing")"
check "rule: courtesy never holds"        ALLOW "$(run  "$R" "echo src/ui")"

# A cleared ask releases it. Without this the hook cannot tell "nobody asked"
# from "asked, ruled Ready, shipped" and would block the second one forever.
cat > "$R/.humangated/CLEARED" <<EOF
# Rulings received. Generated by HumanGated — do not hand-edit.
3f2a1b8c-0000-4000-8000-000000000009	$NOW	src/billing/**
EOF
check "rule: a cleared ruling releases"   ALLOW "$(run  "$R" "git commit -m done")"
rm -f "$R/.humangated/CLEARED"
check "rule: removing the ruling re-holds" DENY "$(run  "$R" "git commit -m again")"

# The failure this whole file exists for, in its new home: a rules ledger that
# matches nothing must not silently permit everything it was meant to hold.
cat > "$R/.humangated/RULES" <<EOF
src/billing/**	required	-	-
EOF
check "rule: ** still matches a subpath"  DENY  "$(run  "$R" "git commit -m x")"

cat > "$R/.humangated/RULES" <<EOF
docs/**	required	-	-
EOF
check "rule: unrelated glob does not hold" ALLOW "$(run  "$R" "git commit -m x")"

rm -f "$R/.humangated/RULES"
check "rule: no rules ledger allows"      ALLOW "$(run  "$R" "git commit -m x")"

printf '\n%d passed, %d failed\n' "$pass" "$fail"
rm -rf "$(dirname "$T")" "$(dirname "$R")"
[ "$fail" -eq 0 ]
